### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by keverw** [parro-it/electron-input-menu#5]
Hey, cool plugin.

I wish there was a way to add menu items...

So like after paste, I'd like to add "Paste and Match Style". Then I would like to add Transformations and Speech menu(Mac). 

Transformations(Upper case, lowercase, capitalize - change selected text)  and Speech be in it's own separated area(Start and Stop Speaking).

Not sure if you'd be interested in adding some sot of API to tweak the menu. Right now it seems like it'd have to just make a fork and manually edit it - which not sure if I'd want to go that route 100% yet..

**Comment by parro-it** [comment]
Thank you! This module is already implemented as a plugin for [electron-contextmenu-middleware](https://github.com/parro-it/electron-contextmenu-middleware). 

It allow you to define plugins that appends custom menu item to the any context menu. Give it a look, you can use it to define all the menu items you described and show them on the same context menu as `electron-input-menu`. Post an issue there if you get stuck, I will be happy to give you help & guidance...
