### ISSUE TITLE
Customize isEditable

### ISSUE THREAD

**Issue by Kagami** [parro-it/electron-input-menu#8]
Hi. Is there any way to prevent menu popup for certain input elements?

**Comment by parro-it** [comment]
I think we could use an ad-hoc attribute, e.g. 'no-menu'. 
Howe could it be named?

**Comment by Kagami** [comment]
Maybe `<input data-electron-no-input-menu />`? Or export/make possible to change `isEditable` function by the module user.

**Comment by Kagami** [comment]
Would you like a PR for that?

**Comment by parro-it** [comment]
@Kagami that would be beautiful 😄 . Go on with your idea of making isEditable configurable.

You can accept it as an argument, and default to the actual implementation
